"""Bilingual (Hebrew / English) text for findings and report chrome.

The analysis engine only ever emits stable codes, so the same report can be
rendered in any language without re-running the analysis.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from .models import Finding

LANGUAGES = ("he", "en")
DEFAULT_LANGUAGE = "he"


@dataclass(frozen=True)
class MessageText:
    title: str
    detail: str
    fix: str


def format_time(seconds: float | None) -> str:
    if seconds is None:
        return "-"
    seconds = max(0.0, float(seconds))
    minutes, rest = divmod(seconds, 60)
    return f"{int(minutes)}:{rest:04.1f}"


CATEGORY_LABELS: dict[str, dict[str, str]] = {
    "hook": {"he": "פתיח (3 השניות הראשונות)", "en": "Hook (first 3 seconds)"},
    "pacing": {"he": "קצב ועריכה", "en": "Pacing & editing"},
    "audio": {"he": "אודיו", "en": "Audio"},
    "visual": {"he": "איכות תמונה", "en": "Image quality"},
    "framing": {"he": "פורמט ומסגור", "en": "Format & framing"},
    "duration": {"he": "אורך הסרטון", "en": "Duration"},
}

SEVERITY_LABELS: dict[str, dict[str, str]] = {
    "critical": {"he": "קריטי", "en": "Critical"},
    "warning": {"he": "לשיפור", "en": "Warning"},
    "info": {"he": "לתשומת לב", "en": "Note"},
    "good": {"he": "עובד טוב", "en": "Working well"},
}

UI: dict[str, dict[str, str]] = {
    "he": {
        "report_title": "דוח ניתוח וידאו",
        "overall": "ציון כולל",
        "platform": "פלטפורמה",
        "file": "קובץ",
        "grade": "דירוג",
        "what_works": "מה עובד טוב",
        "what_to_fix": "מה לא עובד",
        "priorities": "3 התיקונים החשובים ביותר",
        "categories": "ציונים לפי קטגוריה",
        "metrics": "מטריקות מפורטות",
        "thumbnails": "פריימים מומלצים לתמונה ראשית",
        "media": "פרטי הקובץ",
        "at": "בזמן",
        "fix_prefix": "מה לעשות",
        "no_issues": "לא נמצאו בעיות משמעותיות. מצוין.",
        "no_strengths": "לא נמצאו נקודות חוזק בולטות.",
        "score_unit": "מתוך 100",
        "category": "קטגוריה",
        "score": "ציון",
        "weight": "משקל",
        "metric": "מדד",
        "value": "ערך",
        "time": "זמן",
        "generated_by": "נוצר על ידי videosai",
        "duration": "אורך",
        "resolution": "רזולוציה",
        "fps": "פריימים בשנייה",
        "audio_track": "פסקול",
        "audio_yes": "קיים",
        "audio_no": "חסר",
    },
    "en": {
        "report_title": "Video analysis report",
        "overall": "Overall score",
        "platform": "Platform",
        "file": "File",
        "grade": "Grade",
        "what_works": "What works",
        "what_to_fix": "What does not work",
        "priorities": "Top 3 fixes",
        "categories": "Scores by category",
        "metrics": "Detailed metrics",
        "thumbnails": "Suggested cover frames",
        "media": "File details",
        "at": "at",
        "fix_prefix": "Do this",
        "no_issues": "No significant issues found. Great.",
        "no_strengths": "No standout strengths found.",
        "score_unit": "out of 100",
        "category": "Category",
        "score": "Score",
        "weight": "Weight",
        "metric": "Metric",
        "value": "Value",
        "time": "Time",
        "generated_by": "Generated by videosai",
        "duration": "Duration",
        "resolution": "Resolution",
        "fps": "Frames per second",
        "audio_track": "Audio track",
        "audio_yes": "present",
        "audio_no": "missing",
    },
}

METRIC_LABELS: dict[str, dict[str, str]] = {
    "cuts_in_hook": {"he": "חתכים בפתיח", "en": "Cuts in hook"},
    "hook_motion": {"he": "תנועה בפתיח", "en": "Hook motion"},
    "motion_overall": {"he": "תנועה ממוצעת", "en": "Average motion"},
    "hook_brightness": {"he": "בהירות הפתיח", "en": "Hook brightness"},
    "hook_sharpness": {"he": "חדות הפתיח", "en": "Hook sharpness"},
    "lead_in_silence": {"he": "שקט בפתיחה (שנ')", "en": "Lead-in silence (s)"},
    "cuts": {"he": "מספר חתכים", "en": "Cuts"},
    "cuts_per_minute": {"he": "חתכים לדקה", "en": "Cuts per minute"},
    "longest_static_seconds": {"he": "השהיה הארוכה ביותר (שנ')", "en": "Longest static shot (s)"},
    "integrated_lufs": {"he": "עוצמה משוקלטת (LUFS)", "en": "Integrated loudness (LUFS)"},
    "loudness_range": {"he": "טווח דינמי (LU)", "en": "Loudness range (LU)"},
    "true_peak_db": {"he": "שיא אמיתי (dBTP)", "en": "True peak (dBTP)"},
    "silence_ratio": {"he": "אחוז שקט", "en": "Silence ratio"},
    "long_gaps": {"he": "שתיקות ארוכות", "en": "Long silent gaps"},
    "sample_rate": {"he": "תדר דגימה", "en": "Sample rate"},
    "sharpness": {"he": "חדות חציונית", "en": "Median sharpness"},
    "brightness": {"he": "בהירות חציונית", "en": "Median brightness"},
    "contrast": {"he": "ניגודיות", "en": "Contrast"},
    "saturation": {"he": "רוויית צבע", "en": "Saturation"},
    "clipped_highlights": {"he": "אחוז פיקסלים שרופים", "en": "Clipped highlights"},
    "dark_seconds": {"he": "שניות חשוכות", "en": "Dark seconds"},
    "aspect_ratio": {"he": "יחס גובה-רוחב", "en": "Aspect ratio"},
    "resolution": {"he": "רזולוציה", "en": "Resolution"},
    "fps": {"he": "פריימים בשנייה", "en": "Frames per second"},
    "bits_per_pixel": {"he": "ביטים לפיקסל", "en": "Bits per pixel"},
    "safe_zone_top_ratio": {"he": "עומס באזור העליון", "en": "Top safe-zone load"},
    "safe_zone_bottom_ratio": {"he": "עומס באזור התחתון", "en": "Bottom safe-zone load"},
    "duration": {"he": "אורך (שנ')", "en": "Duration (s)"},
    "ideal_range": {"he": "טווח מומלץ (שנ')", "en": "Recommended range (s)"},
}

# code -> language -> (title, detail, fix)
CATALOG: dict[str, dict[str, tuple[str, str, str]]] = {
    # ---------------------------------------------------------------- hook
    "HOOK_DEAD_AIR": {
        "he": (
            "הסרטון נפתח ב־{lead_in:.1f} שניות של שקט",
            "אין קול בהתחלה, וזה בדיוק החלון שבו הצופה מחליט אם להישאר.",
            "חתוך את השקט בהתחלה כך שהמשפט הראשון יישמע בתוך 0.3 שניות.",
        ),
        "en": (
            "The video opens with {lead_in:.1f}s of silence",
            "There is no sound at the start, exactly when the viewer decides whether to stay.",
            "Trim the lead-in so the first words land within 0.3s.",
        ),
    },
    "HOOK_STATIC": {
        "he": (
            "הפתיח סטטי מדי",
            "התנועה בפריים ב-3 השניות הראשונות ({hook_motion:.1f}) נמוכה משמעותית מהממוצע בסרטון ({motion_overall:.1f}).",
            "פתח בתנועה: זום, חתך מהיר, או מעבר שמראה מיד מה קורה בסרטון.",
        ),
        "en": (
            "The hook is too static",
            "Motion in the first 3 seconds ({hook_motion:.1f}) is well below the video average ({motion_overall:.1f}).",
            "Open with movement: a push-in, a quick cut, or a shot that shows the payoff immediately.",
        ),
    },
    "HOOK_NO_CUT": {
        "he": (
            "אין חתך אחד בפתיח",
            "3 השניות הראשונות הן שוט אחד רצוף, מה שמקשה על שמירת קשב בפורמט קצר.",
            "הוסף חתך אחד לפחות בשנייה הראשונה או השנייה.",
        ),
        "en": (
            "No cut in the hook",
            "The first 3 seconds are a single continuous shot, which is hard to sustain in short form.",
            "Add at least one cut within the first two seconds.",
        ),
    },
    "HOOK_DARK_OPEN": {
        "he": (
            "הפתיח חשוך",
            "הבהירות הממוצעת בפתיח היא {hook_brightness:.0f} מתוך 255.",
            "האר את הפריים הראשון או התחל מהשוט המואר ביותר שיש לך.",
        ),
        "en": (
            "Dark opening",
            "Average brightness in the hook is {hook_brightness:.0f} out of 255.",
            "Brighten the opening frame or start from your best-lit shot.",
        ),
    },
    "HOOK_SOFT_FOCUS_OPEN": {
        "he": (
            "הפריים הראשון לא חד",
            "מדד החדות בפתיח הוא {hook_sharpness:.0f} (מתחת ל־{threshold:.0f} נראה מרוח).",
            "נעל פוקוס לפני ההקלטה, או חתוך את השניות שבהן העדשה עוד מחפשת פוקוס.",
        ),
        "en": (
            "The first frame is not sharp",
            "Hook sharpness is {hook_sharpness:.0f} (below {threshold:.0f} looks soft).",
            "Lock focus before recording, or trim the seconds where the lens is still hunting.",
        ),
    },
    "HOOK_STRONG": {
        "he": (
            "פתיח חזק",
            "יש תנועה, קול נכנס מיד והפריים קריא. זה מה שמחזיק צופים.",
            "",
        ),
        "en": (
            "Strong hook",
            "There is motion, audio starts immediately and the frame is readable. This is what holds viewers.",
            "",
        ),
    },
    # -------------------------------------------------------------- pacing
    "PACING_SLOW": {
        "he": (
            "הקצב איטי לפלטפורמה",
            "{cuts_per_minute:.0f} חתכים לדקה, כשהטווח המומלץ ל{platform} הוא {min_cpm:.0f}–{max_cpm:.0f}.",
            "הדק את העריכה: הורד מילות מעבר, נשימות והתחלות משפט שלא מוסיפות.",
        ),
        "en": (
            "Pacing is slow for this platform",
            "{cuts_per_minute:.0f} cuts per minute; the recommended range for {platform} is {min_cpm:.0f}-{max_cpm:.0f}.",
            "Tighten the edit: drop filler words, breaths and false starts.",
        ),
    },
    "PACING_FROZEN_SHOT": {
        "he": (
            "יש שוט קפוא של {longest_static:.1f} שניות",
            "מ־{at_fmt} הפריים כמעט לא משתנה, וזו נקודה טיפוסית לנשירה.",
            "חתוך את הקטע, הוסף b-roll, זום עדין או כתובית שמחזיקה את העין.",
        ),
        "en": (
            "There is a {longest_static:.1f}s frozen shot",
            "From {at_fmt} the frame barely changes, a typical drop-off point.",
            "Cut it down, add b-roll, a slow push-in, or an on-screen line to hold the eye.",
        ),
    },
    "PACING_FRANTIC": {
        "he": (
            "העריכה מהירה מדי",
            "{cuts_per_minute:.0f} חתכים לדקה - מעל {max_cpm:.0f}, ולצופה קשה לעקוב.",
            "השאר שוטים מרכזיים לפחות 1.5 שניות כדי שהמסר ייקלט.",
        ),
        "en": (
            "The edit is too frantic",
            "{cuts_per_minute:.0f} cuts per minute, above {max_cpm:.0f}, which is hard to follow.",
            "Let key shots breathe for at least 1.5 seconds so the message registers.",
        ),
    },
    "PACING_GOOD": {
        "he": (
            "קצב טוב",
            "{cuts_per_minute:.0f} חתכים לדקה, בתוך הטווח שעובד ב{platform}, ובלי שוטים קפואים.",
            "",
        ),
        "en": (
            "Good pacing",
            "{cuts_per_minute:.0f} cuts per minute, inside the range that works on {platform}, with no frozen shots.",
            "",
        ),
    },
    "PACING_STABLE": {
        "he": (
            "אין נפילות קצב",
            "לא נמצא שוט קפוא ארוך מ־{max_static:.0f} שניות.",
            "",
        ),
        "en": (
            "No pacing dips",
            "No frozen shot longer than {max_static:.0f}s was found.",
            "",
        ),
    },
    # --------------------------------------------------------------- audio
    "AUDIO_MISSING": {
        "he": (
            "אין פסקול בקובץ",
            "לסרטון אין ערוץ אודיו בכלל. בפידים שמתנגנים עם קול זו נשירה כמעט מיידית.",
            "הוסף קריינות, מוזיקה או סאונד סביבה - ובכל מקרה כתוביות.",
        ),
        "en": (
            "The file has no audio",
            "There is no audio stream at all. On sound-on feeds this means an immediate drop-off.",
            "Add narration, music or ambience, and captions either way.",
        ),
    },
    "AUDIO_QUIET": {
        "he": (
            "האודיו חלש ב־{delta:.1f} dB",
            "העוצמה המשוקלטת היא {lufs:.1f} LUFS מול יעד של {target:.1f} LUFS.",
            "נרמל ל־{target:.1f} LUFS (למשל ffmpeg loudnorm) לפני העלאה.",
        ),
        "en": (
            "Audio is {delta:.1f} dB too quiet",
            "Integrated loudness is {lufs:.1f} LUFS against a {target:.1f} LUFS target.",
            "Normalize to {target:.1f} LUFS (for example ffmpeg loudnorm) before uploading.",
        ),
    },
    "AUDIO_LOUD": {
        "he": (
            "האודיו חזק ב־{delta:.1f} dB",
            "העוצמה היא {lufs:.1f} LUFS מול יעד של {target:.1f} LUFS, והפלטפורמה תחליש אותו ותשטח את הדינמיקה.",
            "נרמל ל־{target:.1f} LUFS במקום לסמוך על ההחלשה האוטומטית.",
        ),
        "en": (
            "Audio is {delta:.1f} dB too loud",
            "Loudness is {lufs:.1f} LUFS against a {target:.1f} LUFS target; the platform will turn it down and flatten the dynamics.",
            "Normalize to {target:.1f} LUFS instead of relying on automatic gain.",
        ),
    },
    "AUDIO_CLIPPING": {
        "he": (
            "האודיו מתפוצץ (clipping)",
            "השיא האמיתי הוא {true_peak:.1f} dBTP, מה שיוצר עיוות בדיבור ובבאסים.",
            "השאר את השיא ב־-1 dBTP ומטה, עם לימיטר לפני הייצוא.",
        ),
        "en": (
            "Audio is clipping",
            "True peak is {true_peak:.1f} dBTP, which distorts speech and bass.",
            "Keep peaks at -1 dBTP or lower with a limiter before export.",
        ),
    },
    "AUDIO_DEAD_GAPS": {
        "he": (
            "{gaps} שתיקות ארוכות באמצע",
            "יש קטעים ללא קול שאורכם מעל {threshold:.1f} שניות ({times_fmt}).",
            "חתוך את השתיקות או שתול מתחתן מוזיקה / סאונד עדין.",
        ),
        "en": (
            "{gaps} long silent gaps",
            "There are silent stretches longer than {threshold:.1f}s ({times_fmt}).",
            "Cut the gaps or lay music / light ambience underneath.",
        ),
    },
    "AUDIO_OVERCOMPRESSED": {
        "he": (
            "האודיו שטוח",
            "הטווח הדינמי הוא {lra:.1f} LU בלבד, מה שנשמע עייף ומכני.",
            "הפחת דחיסה, או תן להדגשות להישאר חזקות יותר מהשאר.",
        ),
        "en": (
            "Audio is flat",
            "The loudness range is only {lra:.1f} LU, which sounds tiring and mechanical.",
            "Ease off the compression, or let emphasis stay louder than the rest.",
        ),
    },
    "AUDIO_LOW_SAMPLE_RATE": {
        "he": (
            "תדר דגימה נמוך",
            "הפסקול נדגם ב־{sample_rate} Hz, מה שגורם לצליל עמום.",
            "ייצא ב־48kHz (או 44.1kHz לפחות).",
        ),
        "en": (
            "Low sample rate",
            "The audio is sampled at {sample_rate} Hz, which sounds muffled.",
            "Export at 48kHz (or at least 44.1kHz).",
        ),
    },
    "AUDIO_GOOD": {
        "he": (
            "אודיו במקום",
            "{lufs:.1f} LUFS, בלי clipping ובלי שתיקות ארוכות.",
            "",
        ),
        "en": (
            "Audio is in good shape",
            "{lufs:.1f} LUFS, no clipping and no long silences.",
            "",
        ),
    },
    # -------------------------------------------------------------- visual
    "VISUAL_SOFT_FOCUS": {
        "he": (
            "התמונה לא חדה",
            "מדד החדות החציוני הוא {sharpness:.0f} (מתחת ל־{threshold:.0f} נתפס מרוח או דחוס מדי).",
            "נקה את העדשה, נעל פוקוס וייצא בביטרייט גבוה יותר.",
        ),
        "en": (
            "The image is soft",
            "Median sharpness is {sharpness:.0f} (below {threshold:.0f} reads as blurry or over-compressed).",
            "Clean the lens, lock focus, and export at a higher bitrate.",
        ),
    },
    "VISUAL_UNDEREXPOSED": {
        "he": (
            "התמונה חשוכה",
            "הבהירות החציונית היא {brightness:.0f} מתוך 255.",
            "הוסף מקור אור מלפנים, או הרם חשיפה וצללים בעריכה.",
        ),
        "en": (
            "The image is underexposed",
            "Median brightness is {brightness:.0f} out of 255.",
            "Add a front light source, or lift exposure and shadows in the edit.",
        ),
    },
    "VISUAL_OVEREXPOSED": {
        "he": (
            "יש אזורים שרופים בתמונה",
            "{clipped:.1f}% מהפיקסלים בלבן מלא, כלומר פרטים שאבדו.",
            "הורד חשיפה, הזז את מקור האור או הוסף דיפיוזר.",
        ),
        "en": (
            "The image has blown highlights",
            "{clipped:.1f}% of pixels are pure white, meaning lost detail.",
            "Lower exposure, move the light source, or add diffusion.",
        ),
    },
    "VISUAL_FLAT": {
        "he": (
            "ניגודיות נמוכה",
            "פיזור הבהירות הוא {contrast:.0f}, והתמונה נראית אפורה ושטוחה.",
            "הרם ניגודיות קלות בעריכה והפרד בין הנושא לרקע.",
        ),
        "en": (
            "Low contrast",
            "Brightness spread is {contrast:.0f}, so the image looks grey and flat.",
            "Raise contrast slightly in the edit and separate subject from background.",
        ),
    },
    "VISUAL_DESATURATED": {
        "he": (
            "צבעים דהויים",
            "רוויית הצבע הממוצעת היא {saturation:.2f}.",
            "אם זו לא בחירה אמנותית, הוסף רוויה או צור אקצנט צבע אחד בולט.",
        ),
        "en": (
            "Washed-out colours",
            "Average saturation is {saturation:.2f}.",
            "Unless it is a deliberate look, add saturation or introduce one strong accent colour.",
        ),
    },
    "VISUAL_DARK_SEGMENTS": {
        "he": (
            "{segments} קטעים חשוכים",
            "סך {dark_seconds:.1f} שניות מתחת לסף החשיכה ({times_fmt}).",
            "האר או קצר את הקטעים האלה - שם הצופים נושרים.",
        ),
        "en": (
            "{segments} dark segments",
            "A total of {dark_seconds:.1f}s below the darkness threshold ({times_fmt}).",
            "Brighten or shorten these parts, this is where viewers leave.",
        ),
    },
    "VISUAL_GOOD": {
        "he": (
            "תמונה נקייה",
            "חדות, חשיפה וניגודיות בטווח תקין.",
            "",
        ),
        "en": (
            "Clean image",
            "Sharpness, exposure and contrast are all in a healthy range.",
            "",
        ),
    },
    # ------------------------------------------------------------- framing
    "FRAMING_ASPECT": {
        "he": (
            "יחס המסך לא מתאים ל{platform}",
            "הסרטון ב־{actual:.2f} ({width}x{height}) והפלטפורמה מצפה ל־{target:.2f}.",
            "ייצא מחדש ביחס {target:.2f} במקום להסתמך על חיתוך אוטומטי.",
        ),
        "en": (
            "Aspect ratio does not match {platform}",
            "The video is {actual:.2f} ({width}x{height}) while the platform expects {target:.2f}.",
            "Re-export at {target:.2f} instead of relying on automatic cropping.",
        ),
    },
    "FRAMING_LOW_RES": {
        "he": (
            "רזולוציה נמוכה",
            "{width}x{height} - מתחת ל־{min_height}p שהפלטפורמה מעדיפה.",
            "צלם וייצא לפחות ב־{min_height}p.",
        ),
        "en": (
            "Low resolution",
            "{width}x{height} is below the {min_height}p the platform prefers.",
            "Shoot and export at {min_height}p or higher.",
        ),
    },
    "FRAMING_LOW_FPS": {
        "he": (
            "מעט פריימים בשנייה",
            "{fps:.1f} fps, מתחת ל־{min_fps:.0f} fps, והתנועה נראית קטועה.",
            "ייצא ב־30 fps ומעלה.",
        ),
        "en": (
            "Low frame rate",
            "{fps:.1f} fps is below {min_fps:.0f} fps, so motion looks choppy.",
            "Export at 30 fps or higher.",
        ),
    },
    "FRAMING_SAFE_ZONE_TOP": {
        "he": (
            "תוכן ב־{percent:.0f}% העליונים של הפריים",
            "האזור הזה מכוסה בממשק הפלטפורמה, וכתוביות או גרפיקה שם ייחסמו.",
            "הזז טקסטים וגרפיקה למרכז הפריים.",
        ),
        "en": (
            "Content in the top {percent:.0f}% of the frame",
            "That band is covered by the platform UI, so text or graphics there get hidden.",
            "Move text and graphics toward the centre of the frame.",
        ),
    },
    "FRAMING_SAFE_ZONE_BOTTOM": {
        "he": (
            "תוכן ב־{percent:.0f}% התחתונים של הפריים",
            "שם יושבים הכיתוב, הכפתורים ושם המשתמש של הפלטפורמה.",
            "הרם את הכתוביות והגרפיקה מעל האזור הזה.",
        ),
        "en": (
            "Content in the bottom {percent:.0f}% of the frame",
            "That is where the caption, buttons and handle sit.",
            "Lift captions and graphics above that band.",
        ),
    },
    "FRAMING_LOW_BITRATE": {
        "he": (
            "ביטרייט נמוך לרזולוציה",
            "{bpp:.3f} ביטים לפיקסל, מה שגורם לארטיפקטים בתנועה מהירה.",
            "העלה את הביטרייט בייצוא (לפחות 8 Mbps ל־1080p).",
        ),
        "en": (
            "Low bitrate for the resolution",
            "{bpp:.3f} bits per pixel, which causes artefacts in fast motion.",
            "Raise the export bitrate (at least 8 Mbps for 1080p).",
        ),
    },
    "FRAMING_GOOD": {
        "he": (
            "פורמט מתאים",
            "{width}x{height} ב־{fps:.0f} fps - בדיוק מה ש{platform} מצפה לקבל.",
            "",
        ),
        "en": (
            "Correct format",
            "{width}x{height} at {fps:.0f} fps, exactly what {platform} expects.",
            "",
        ),
    },
    # ------------------------------------------------------------ duration
    "DURATION_SHORT": {
        "he": (
            "הסרטון קצר מהטווח המומלץ",
            "{duration:.1f} שניות, כשהטווח שעובד ב{platform} הוא {min_d:.0f}–{max_d:.0f} שניות.",
            "הוסף הקשר או פאנץ' בסוף כדי להגיע לטווח הזה.",
        ),
        "en": (
            "Shorter than the recommended range",
            "{duration:.1f}s, while the range that works on {platform} is {min_d:.0f}-{max_d:.0f}s.",
            "Add context or a closing payoff to reach that range.",
        ),
    },
    "DURATION_LONG": {
        "he": (
            "הסרטון ארוך מהטווח המומלץ",
            "{duration:.1f} שניות מול {min_d:.0f}–{max_d:.0f} שניות ב{platform}.",
            "קצר לנקודה אחת חדה, או פצל לסדרה.",
        ),
        "en": (
            "Longer than the recommended range",
            "{duration:.1f}s against {min_d:.0f}-{max_d:.0f}s on {platform}.",
            "Trim to a single sharp point, or split into a series.",
        ),
    },
    "DURATION_OVER_LIMIT": {
        "he": (
            "הסרטון עובר את מגבלת הפלטפורמה",
            "{duration:.1f} שניות מול מקסימום של {max_allowed:.0f} שניות ב{platform}.",
            "קצר מתחת למגבלה, אחרת ההעלאה תיחתך או תידחה.",
        ),
        "en": (
            "Over the platform limit",
            "{duration:.1f}s against a {max_allowed:.0f}s maximum on {platform}.",
            "Trim below the limit, otherwise the upload gets cut or rejected.",
        ),
    },
    "DURATION_GOOD": {
        "he": (
            "אורך מתאים",
            "{duration:.1f} שניות, בתוך הטווח המומלץ ל{platform}.",
            "",
        ),
        "en": (
            "Good length",
            "{duration:.1f}s, inside the recommended range for {platform}.",
            "",
        ),
    },
}


def normalize_language(lang: str | None) -> str:
    if not lang:
        return DEFAULT_LANGUAGE
    lang = lang.strip().lower()[:2]
    return lang if lang in LANGUAGES else DEFAULT_LANGUAGE


def ui(key: str, lang: str = DEFAULT_LANGUAGE) -> str:
    lang = normalize_language(lang)
    return UI[lang].get(key, UI["en"].get(key, key))


def category_label(key: str, lang: str = DEFAULT_LANGUAGE) -> str:
    lang = normalize_language(lang)
    return CATEGORY_LABELS.get(key, {}).get(lang, key)


def severity_label(severity: str, lang: str = DEFAULT_LANGUAGE) -> str:
    lang = normalize_language(lang)
    return SEVERITY_LABELS.get(severity, {}).get(lang, severity)


def metric_label(key: str, lang: str = DEFAULT_LANGUAGE) -> str:
    lang = normalize_language(lang)
    return METRIC_LABELS.get(key, {}).get(lang, key)


def _auto_params(finding: Finding) -> dict[str, Any]:
    return {
        "at_fmt": format_time(finding.at),
        "times_fmt": ", ".join(format_time(t) for t in finding.timestamps),
    }


def _localize_platform(params: dict[str, Any], lang: str) -> dict[str, Any]:
    """Findings carry a platform key; reports show the localized label."""
    from .platforms import PLATFORMS

    platform = PLATFORMS.get(str(params.get("platform")))
    if platform is None:
        return params
    return {**params, "platform": platform.label(lang)}


def render(finding: Finding, lang: str = DEFAULT_LANGUAGE) -> MessageText:
    """Turn a finding into human readable title / detail / fix."""
    lang = normalize_language(lang)
    entry = CATALOG.get(finding.code)
    if entry is None:
        return MessageText(title=finding.code, detail="", fix="")
    title, detail, fix = entry.get(lang) or entry["en"]
    params = _localize_platform({**_auto_params(finding), **finding.params}, lang)
    return MessageText(
        title=_safe_format(title, params),
        detail=_safe_format(detail, params),
        fix=_safe_format(fix, params),
    )


def _safe_format(template: str, params: dict[str, Any]) -> str:
    try:
        return template.format(**params)
    except (KeyError, IndexError, ValueError):
        # A missing parameter should never hide the rest of the report.
        return template
